version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "demo-task"
        LoadBalancerInfo:
          ContainerName: "demo-container"
          ContainerPort: 8080
