version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "java-demo-ecr"
    IMAGE_TAG: "latest"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - REPO_URI=$(aws ecr describe-repositories --repository-names "$IMAGE_REPO_NAME" --region $AWS_REGION --query "repositories[0].repositoryUri" --output text) || true
      - if [ -z "$REPO_URI" ]; then aws ecr create-repository --repository-name "$IMAGE_REPO_NAME" --region $AWS_REGION; fi
      - REPO_URI=$(aws ecr describe-repositories --repository-names "$IMAGE_REPO_NAME" --region $AWS_REGION --query "repositories[0].repositoryUri" --output text)
  build:
    commands:
      - echo Build started on `date`
      - mvn -B -DskipTests package
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPO_URI:$IMAGE_TAG
      - printf '[{"name":"java-web-app-container","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
